// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxKua7_jUZoqqiYpLO5jH0WBmjteuPNPk',
    appId: '1:137708856251:web:90b2933d1457144a42da9e',
    messagingSenderId: '137708856251',
    projectId: 'vehicle-tracking-system-9de9d',
    authDomain: 'vehicle-tracking-system-9de9d.firebaseapp.com',
    storageBucket: 'vehicle-tracking-system-9de9d.firebasestorage.app',
    measurementId: 'G-ZHD35XTJ58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKxnxSJyyaahb11SvCL8m9F_zBeKue3yQ',
    appId: '1:137708856251:android:c1b6274c4c41ab4242da9e',
    messagingSenderId: '137708856251',
    projectId: 'vehicle-tracking-system-9de9d',
    storageBucket: 'vehicle-tracking-system-9de9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-wOIwUfEAtigjlmO6FAFBqNdJo0BooKE',
    appId: '1:137708856251:ios:5351558d6c7864b842da9e',
    messagingSenderId: '137708856251',
    projectId: 'vehicle-tracking-system-9de9d',
    storageBucket: 'vehicle-tracking-system-9de9d.firebasestorage.app',
    iosBundleId: 'com.example.vehicleTrackingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-wOIwUfEAtigjlmO6FAFBqNdJo0BooKE',
    appId: '1:137708856251:ios:5351558d6c7864b842da9e',
    messagingSenderId: '137708856251',
    projectId: 'vehicle-tracking-system-9de9d',
    storageBucket: 'vehicle-tracking-system-9de9d.firebasestorage.app',
    iosBundleId: 'com.example.vehicleTrackingSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxKua7_jUZoqqiYpLO5jH0WBmjteuPNPk',
    appId: '1:137708856251:web:9392c381ca64fc5e42da9e',
    messagingSenderId: '137708856251',
    projectId: 'vehicle-tracking-system-9de9d',
    authDomain: 'vehicle-tracking-system-9de9d.firebaseapp.com',
    storageBucket: 'vehicle-tracking-system-9de9d.firebasestorage.app',
    measurementId: 'G-5SF22S8TS2',
  );
}
